vars:
  - batch/test_stations.json

stages:
  choose_test_stations:
    cmd: julia --project=batch batch/test_stations.jl choose ./data ./data/test_stations.csv
      --epsg=5072 --maxgap=4
    deps:
    - batch/test_stations.jl
    - data/data2015
    - data/isdList.csv
    - src/preprocessing.jl
    outs:
    - data/test_stations.csv:
        cache: false
  test_stations_json:
    cmd: julia --project=batch batch/test_stations.jl tojson ./data/test_stations.csv ./batch/test_stations.json
    deps:
      - batch/test_stations.jl
      - data/test_stations.csv
    outs:
      - batch/test_stations.json:
          cache: false
  kernelfit_SExSE:
    foreach: ${ICAO} # from batch/test_stations.json
    do:
      cmd: julia --project=batch batch/pipeline0_kernelfit.jl ${item} SExSE ./data ./data/outputs
        --timelimit=Inf --knearest=5
      deps:
      - batch/pipeline0_kernelfit.jl
      - data/data2015
      - src/preprocessing.jl
      outs:
      - data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json:
          cache: false
  nearby_predictions_SExSE:
    foreach: ${ICAO}
    do:
      cmd: julia --project=batch batch/pipeline1.jl ${item} SExSE ./data ./data/outputs
        data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json --knearest=5
      deps:
      - batch/pipeline1.jl
      - data/data2015
      - data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json
      - src/GPrealisations.jl
      - src/predict_from_nearby.jl
      - src/preprocessing.jl
      outs:
      - data/outputs/predictions_from_nearby/mll/SExSE/${item}
  # compilestan:
    # cmd: julia --project=batch batch/pipeline2.jl compilestan KBDL SExSE 1 ./data
      # ./data/outputs/compiledstan
    # deps:
    # - batch/pipeline2.jl
    # - src/stan_impute.jl
    # outs:
    # - data/outputs/compiledstan/hr_measure/mll/SExSE/17/KBDL/725080_14740_KBDL_2015-01-01_to_2015-01-10/imputation
    # - data/outputs/compiledstan/hr_measure/mll/SExSE/17/KBDL/725080_14740_KBDL_2015-01-01_to_2015-01-10/imputation.hpp
    # - data/outputs/compiledstan/hr_measure/mll/SExSE/17/KBDL/725080_14740_KBDL_2015-01-01_to_2015-01-10/imputation.stan
