vars:
  - batch/test_stations.json

stages:
  choose_test_stations:
    cmd: julia --project=batch batch/test_stations.jl choose ./data ./data/test_stations.csv
      --epsg=5072 --maxgap=4
    deps:
    - batch/test_stations.jl
    - data/data2015
    - data/isdList.csv
    - src/preprocessing.jl
    outs:
    - data/test_stations.csv:
        cache: false
  test_stations_json:
    cmd: julia --project=batch batch/test_stations.jl tojson ./data/test_stations.csv ./batch/test_stations.json
    deps:
      - batch/test_stations.jl
      - data/test_stations.csv
    outs:
      - batch/test_stations.json:
          cache: false
  kernelfit_diurnal:
    foreach: ${ICAO} # from batch/test_stations.json
    do:
      cmd: julia --project=batch batch/pipeline0_kernelfit.jl ${item} diurnal ./data ./data/outputs
        --timelimit=Inf --knearest=5
      deps:
      - batch/pipeline0_kernelfit.jl
      - data/data2015
      - src/preprocessing.jl
      - src/covariance.jl
      - src/fitted_kernel.jl
      outs:
      - data/outputs/fitted_kernel/mll/diurnal/hyperparams_diurnal_${item}.json:
          cache: false
  kernelfit_SExSE:
    foreach: ${ICAO} # from batch/test_stations.json
    do:
      cmd: julia --project=batch batch/pipeline0_kernelfit.jl ${item} SExSE ./data ./data/outputs
        --timelimit=Inf --knearest=5
      deps:
      - batch/pipeline0_kernelfit.jl
      - data/data2015
      - src/preprocessing.jl
      - src/covariance.jl
      - src/fitted_kernel.jl
      outs:
      - data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json:
          cache: false
  kernelfit_matern:
    foreach: ${ICAO} # from batch/test_stations.json
    do:
      cmd: julia --project=batch batch/pipeline0_kernelfit.jl ${item} matern ./data ./data/outputs
        --timelimit=Inf --knearest=5
      deps:
      - batch/pipeline0_kernelfit.jl
      - data/data2015
      - src/preprocessing.jl
      - src/covariance.jl
      - src/fitted_kernel.jl
      outs:
      - data/outputs/fitted_kernel/mll/matern/hyperparams_matern_${item}.json:
          cache: false
  kernelfit_matern_crossval:
    foreach: ${ICAO} # from batch/test_stations.json
    do:
      cmd: julia --project=batch batch/pipeline0_kernelfit.jl ${item} matern ./data ./data/outputs
        --timelimit=Inf --knearest=5 --crossval
      deps:
      - batch/pipeline0_kernelfit.jl
      - data/data2015
      - src/preprocessing.jl
      - src/covariance.jl
      - src/fitted_kernel.jl
      outs:
      - data/outputs/fitted_kernel/crossval/matern/hyperparams_matern_${item}.json:
          cache: false
  nearby_predictions_SExSE:
    foreach: ${ICAO}
    do:
      cmd: julia --project=batch batch/pipeline1.jl ${item} SExSE ./data ./data/outputs
        data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json --knearest=5
      deps:
      - batch/pipeline1.jl
      - data/data2015
      - data/outputs/fitted_kernel/mll/SExSE/hyperparams_SExSE_${item}.json
      - src/GPrealisations.jl
      - src/predict_from_nearby.jl
      - src/preprocessing.jl
      outs:
      - data/outputs/predictions_from_nearby/mll/SExSE/${item}
  nearby_predictions_diurnal:
    foreach: ${ICAO}
    do:
      cmd: julia --project=batch batch/pipeline1.jl ${item} diurnal ./data ./data/outputs
        data/outputs/fitted_kernel/mll/diurnal/hyperparams_diurnal_${item}.json --knearest=5
      deps:
      - batch/pipeline1.jl
      - data/data2015
      - data/outputs/fitted_kernel/mll/diurnal/hyperparams_diurnal_${item}.json
      - src/GPrealisations.jl
      - src/predict_from_nearby.jl
      - src/preprocessing.jl
      outs:
      - data/outputs/predictions_from_nearby/mll/diurnal/${item}
  compilestan:
    cmd: julia --project=batch batch/pipeline2.jl compilestan ./data/outputs/compiledstan
    deps:
    - batch/pipeline2.jl
    - src/stan_impute.jl
    outs:
    - data/outputs/compiledstan/imputation
    - data/outputs/compiledstan/imputation.hpp
    - data/outputs/compiledstan/imputation.stan
  impute_SExSE:
    foreach: ${ICAO_stanwindows} # from batch/test_stations.json
    do:
      cmd: 
      - mkdir -p ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}
      - cp -RL ./data/outputs/compiledstan/* ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}
      - chmod ug+x ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation
      - chmod ug+x ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation.hpp
      - touch ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation.hpp # prevent recompilation
      - touch ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation # prevent recompilation
      - ls -l ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}
      - julia --project=batch --threads 4 batch/pipeline2.jl impute ${item.ICAO} SExSE ${item.windownum} ./data 
              ./data/outputs/predictions_from_nearby/mll/SExSE/${item.ICAO} 
              ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}
              --ksmoothmax=30 --epsilon=0.05 --seed=${item.windownum}
              --hr_measure_true=17 --hr_measure_impt=17 --stan_days=10
      # remove last 4 lines of Stan output, which contains timings
      # and is therefore not reproducible
      - grep -v ' seconds' ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_1.csv 
                         > ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
      - mv ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
           ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_1.csv
      - grep -v ' seconds' ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_2.csv
                         > ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
      - mv ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
           ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_2.csv
      - grep -v ' seconds' ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_3.csv
                         > ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
      - mv ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
           ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_3.csv
      - grep -v ' seconds' ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_4.csv
                         > ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
      - mv ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/tmp.csv
           ./data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_4.csv
      deps:
      - data/outputs/predictions_from_nearby/mll/SExSE/${item.ICAO}
      - batch/pipeline2.jl
      - src/stan_impute.jl
      - data/outputs/compiledstan/imputation
      - data/outputs/compiledstan/imputation.hpp
      - data/outputs/compiledstan/imputation.stan
      outs:
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_data_1.R
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_data_2.R
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_data_3.R
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_data_4.R
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation.hpp
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation.stan
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_1.csv
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_2.csv
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_3.csv
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/imputation_chain_4.csv
      - data/outputs/imputations/mll/SExSE/hr17/${item.ICAO}/window${item.windownum}/timestamps.csv
